AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Service to verify session tokens for Rentalated clients

Globals:
    Function:
        Timeout: 5

Resources:
    LambdaFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: token_service/
            Handler: app.token_verifier
            Runtime: python3.7
            Events:
                PostRequest:
                    Type: Api
                    Properties:
                        Path: /token_service
                        Method: post

Outputs:
    LambdaFunctionAPI:
      Description: "API Gateway endpoint URL for Prod stage"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/token_service/"

    LambdaFunction:
      Description: "Lambda Function ARN"
      Value: !GetAtt LambdaFunction.Arn

    LambdaFunctionIamRole:
      Description: "Implicit IAM Role for the lambda."
      Value: !GetAtt LambdaFunctionRole.Arn
